name: APIsec

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '26 1 * * 1'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  Trigger_APIsec_scan:
    permissions:
      security-events: write
      actions: read
    runs-on: ubuntu-latest

    steps:
      - name: Run APIsec Scan
        uses: apisec-inc/apisec-run-scan@v1
        with:
          api_token: ${{ secrets.APISEC_TOKEN }}
          project: "VAmPI"
          profile: "Master"
          host: "https://api.natemarcellus.com"
          oas: false
          outputfile: "apisec-results.sarif"

      - name: Upload SARIF results
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: apisec-results.sarif
